name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installation
      run: make install
    - name: Linting
      run: make lint
    - name: Analysing
      run: make analyse
    - name: Testing
      run: make test
    - name: Code climate coverage Action
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: c61aa0ae121789f84f686eeba2f16d8067b71e0b22de24015d1afb671c57d249

