name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installation
      run: make install
    - name: Database creation
      run: make db
    - name: Linting
      run: make lint
    - name: Analysing
      run: make analyse
    - name: Testing
      run: make test
    - name: Code climate coverage Action
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
        debug: true

